-- PricePilot Supabase schema
-- Apply this file in the Supabase SQL editor before enabling real cloud sync.
--
-- Security model:
-- - Supabase Auth owns user identity.
-- - public.account_members maps auth.users.id to a PricePilot account.
-- - Every tenant table is protected by RLS through account_id.
-- - No anon policy is granted for customer data.

create extension if not exists pgcrypto;

create schema if not exists private;
revoke all on schema private from public;
revoke all on schema private from anon;
revoke all on schema private from authenticated;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null default '',
    full_name text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.accounts (
    id bigint generated by default as identity primary key,
    name text not null default 'La mia attivita',
    plan text not null default 'free' check (plan in ('free', 'plus', 'pro')),
    billing_status text not null default 'dev',
    trial_ends_at timestamptz,
    current_period_ends_at timestamptz,
    stripe_customer_id text not null default '',
    stripe_subscription_id text not null default '',
    owner_user_id uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.account_members (
    account_id bigint not null references public.accounts(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    role text not null default 'owner' check (role in ('owner', 'manager', 'viewer')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (account_id, user_id)
);

create table if not exists public.user_consents (
    id uuid primary key default gen_random_uuid(),
    account_id bigint not null,
    user_id uuid not null references auth.users(id) on delete cascade,
    terms_accepted boolean not null default false,
    privacy_accepted boolean not null default false,
    marketing_accepted boolean not null default false,
    terms_version text not null default '2026-07-13',
    privacy_version text not null default '2026-07-13',
    source text not null default 'signup',
    accepted_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(user_id, terms_version, privacy_version)
);

create table if not exists public.properties (
    id uuid primary key default gen_random_uuid(),
    account_id bigint not null,
    local_id bigint not null,
    name text not null,
    platform text not null default 'airbnb',
    listing_url text not null default '',
    listing_id text not null default '',
    city text not null default '',
    latitude double precision,
    longitude double precision,
    min_price numeric not null default 50,
    max_price numeric not null default 500,
    sync_mode text not null default 'advisory',
    strategy text not null default 'balanced',
    plan text not null default 'free' check (plan in ('free', 'plus', 'pro')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(account_id, local_id)
);

create table if not exists public.pricing_rules (
    id uuid primary key default gen_random_uuid(),
    account_id bigint not null,
    property_local_id bigint not null,
    min_price numeric not null default 50,
    max_price numeric not null default 500,
    strategy text not null default 'balanced',
    sync_mode text not null default 'advisory',
    max_change_pct numeric,
    occupancy_low_threshold numeric,
    occupancy_high_threshold numeric,
    source text not null default 'pricepilot_dashboard',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(account_id, property_local_id)
);

create table if not exists public.guardrail_policies (
    id uuid primary key default gen_random_uuid(),
    account_id bigint not null,
    local_id bigint,
    property_local_id bigint not null default 0,
    max_change_pct numeric not null default 0.20,
    require_approval_pct numeric not null default 0.15,
    min_confidence_auto numeric not null default 0.80,
    competitor_outlier_pct numeric not null default 0.60,
    max_daily_auto_changes integer not null default 4,
    auto_enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(account_id, property_local_id)
);

create table if not exists public.price_calendar (
    id uuid primary key default gen_random_uuid(),
    account_id bigint not null,
    local_id bigint,
    property_local_id bigint not null,
    date date not null,
    current_price numeric not null,
    current_price_source text not null default 'manual',
    recommended_price numeric,
    status text not null default 'current',
    decision_log_local_id bigint,
    applied_price numeric,
    notes text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(account_id, property_local_id, date)
);

create table if not exists public.decision_log (
    id uuid primary key default gen_random_uuid(),
    account_id bigint not null,
    local_id bigint not null,
    property_local_id bigint not null,
    timestamp timestamptz not null default now(),
    date date,
    old_price numeric not null,
    new_price numeric not null,
    market_avg numeric,
    competitor_avg numeric,
    occupancy numeric,
    decision text not null default '',
    mode text not null default 'advisory',
    applied boolean not null default false,
    strategy text,
    factors jsonb not null default '{}'::jsonb,
    mpi numeric,
    current_price_source text not null default 'manual',
    data_source text not null default 'demo',
    notes text not null default '',
    tg_message_id text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(account_id, local_id)
);

create table if not exists public.occupancy_history (
    id uuid primary key default gen_random_uuid(),
    account_id bigint not null,
    local_id bigint,
    property_local_id bigint not null,
    date date not null,
    occupancy numeric not null,
    source text not null default 'manual',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(account_id, property_local_id, date)
);

create table if not exists public.market_history (
    id uuid primary key default gen_random_uuid(),
    account_id bigint not null,
    local_id bigint not null,
    property_local_id bigint not null,
    date date not null,
    market_avg numeric,
    market_min numeric,
    market_max numeric,
    market_std numeric,
    competitor_count integer,
    source text not null default 'demo',
    recorded_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(account_id, local_id)
);

create table if not exists public.telegram_links (
    id uuid primary key default gen_random_uuid(),
    account_id bigint not null,
    local_id bigint not null,
    property_local_id bigint not null,
    token text not null,
    chat_id bigint,
    telegram_username text not null default '',
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(account_id, local_id),
    unique(account_id, token)
);

create table if not exists public.telegram_approvals (
    id uuid primary key default gen_random_uuid(),
    account_id bigint not null,
    local_id bigint,
    property_local_id bigint,
    decision_log_local_id bigint not null,
    telegram_link_local_id bigint,
    chat_id bigint,
    telegram_username text not null default '',
    action text not null,
    status text not null,
    source text not null default 'telegram',
    message_id text not null default '',
    callback_query_id text not null default '',
    error text not null default '',
    payload jsonb not null default '{}'::jsonb,
    timestamp timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(account_id, local_id)
);

create table if not exists public.property_integrations (
    id uuid primary key default gen_random_uuid(),
    account_id bigint not null,
    local_id bigint not null,
    property_local_id bigint not null,
    platform text not null,
    listing_url text not null default '',
    listing_id text not null default '',
    is_primary boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(account_id, local_id),
    unique(account_id, property_local_id, platform)
);

create table if not exists public.operation_runs (
    id uuid primary key default gen_random_uuid(),
    account_id bigint not null,
    local_id bigint not null,
    source text not null default 'scheduler',
    status text not null default 'running',
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    next_run_at timestamptz,
    decisions_count integer not null default 0,
    summary jsonb not null default '{}'::jsonb,
    error text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(account_id, local_id)
);

create table if not exists public.audit_events (
    id uuid primary key default gen_random_uuid(),
    account_id bigint not null,
    local_id bigint not null,
    property_local_id bigint,
    timestamp timestamptz not null default now(),
    source text not null default 'system',
    action text not null,
    entity_type text not null default 'system',
    entity_id text not null default '',
    status text not null default 'ok',
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(account_id, local_id)
);

create table if not exists public.notification_preferences (
    id uuid primary key default gen_random_uuid(),
    account_id bigint not null,
    local_id bigint,
    property_local_id bigint not null default 0,
    telegram_enabled boolean not null default true,
    quiet_hours_start text not null default '',
    quiet_hours_end text not null default '',
    daily_digest boolean not null default true,
    approval_alerts boolean not null default true,
    auto_reports boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(account_id, property_local_id)
);

create table if not exists public.notification_log (
    id uuid primary key default gen_random_uuid(),
    account_id bigint not null,
    local_id bigint not null,
    property_local_id bigint,
    timestamp timestamptz not null default now(),
    channel text not null default 'telegram',
    event_type text not null,
    recipient text not null default '',
    status text not null,
    message_id text not null default '',
    error text not null default '',
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(account_id, local_id)
);

-- Compatibility migrations for projects where some tables already existed.
-- CREATE TABLE IF NOT EXISTS does not add missing columns, so we make the
-- schema safe to rerun on partially-created Supabase projects.
alter table if exists public.properties
    add column if not exists account_id bigint,
    add column if not exists local_id bigint,
    add column if not exists name text,
    add column if not exists platform text default 'airbnb',
    add column if not exists listing_url text default '',
    add column if not exists listing_id text default '',
    add column if not exists city text default '',
    add column if not exists latitude double precision,
    add column if not exists longitude double precision,
    add column if not exists min_price numeric default 50,
    add column if not exists max_price numeric default 500,
    add column if not exists sync_mode text default 'advisory',
    add column if not exists strategy text default 'balanced',
    add column if not exists plan text default 'free',
    add column if not exists created_at timestamptz default now(),
    add column if not exists updated_at timestamptz default now();
update public.properties set account_id = 1 where account_id is null;
update public.properties set local_id = 0 where local_id is null;
update public.properties set name = 'Proprieta' where name is null;
update public.properties set platform = 'airbnb' where platform is null;
update public.properties set listing_url = '' where listing_url is null;
update public.properties set listing_id = '' where listing_id is null;
update public.properties set city = '' where city is null;
update public.properties set min_price = 50 where min_price is null;
update public.properties set max_price = 500 where max_price is null;
update public.properties set sync_mode = 'advisory' where sync_mode is null;
update public.properties set strategy = 'balanced' where strategy is null;
update public.properties set plan = 'free' where plan is null;
update public.properties set created_at = now() where created_at is null;
update public.properties set updated_at = now() where updated_at is null;
alter table if exists public.properties
    alter column account_id set not null,
    alter column local_id set not null,
    alter column name set not null,
    alter column platform set not null,
    alter column listing_url set not null,
    alter column listing_id set not null,
    alter column city set not null,
    alter column min_price set not null,
    alter column max_price set not null,
    alter column sync_mode set not null,
    alter column strategy set not null,
    alter column plan set not null,
    alter column created_at set not null,
    alter column updated_at set not null;

alter table if exists public.pricing_rules
    add column if not exists account_id bigint,
    add column if not exists property_local_id bigint,
    add column if not exists min_price numeric default 50,
    add column if not exists max_price numeric default 500,
    add column if not exists strategy text default 'balanced',
    add column if not exists sync_mode text default 'advisory',
    add column if not exists max_change_pct numeric,
    add column if not exists occupancy_low_threshold numeric,
    add column if not exists occupancy_high_threshold numeric,
    add column if not exists source text default 'pricepilot_dashboard',
    add column if not exists created_at timestamptz default now(),
    add column if not exists updated_at timestamptz default now();
update public.pricing_rules set account_id = 1 where account_id is null;
update public.pricing_rules set property_local_id = 0 where property_local_id is null;
update public.pricing_rules set min_price = 50 where min_price is null;
update public.pricing_rules set max_price = 500 where max_price is null;
update public.pricing_rules set strategy = 'balanced' where strategy is null;
update public.pricing_rules set sync_mode = 'advisory' where sync_mode is null;
update public.pricing_rules set source = 'pricepilot_dashboard' where source is null;
update public.pricing_rules set created_at = now() where created_at is null;
update public.pricing_rules set updated_at = now() where updated_at is null;
alter table if exists public.pricing_rules
    alter column account_id set not null,
    alter column property_local_id set not null,
    alter column min_price set not null,
    alter column max_price set not null,
    alter column strategy set not null,
    alter column sync_mode set not null,
    alter column source set not null,
    alter column created_at set not null,
    alter column updated_at set not null;

alter table if exists public.user_consents
    add column if not exists account_id bigint,
    add column if not exists user_id uuid,
    add column if not exists terms_accepted boolean default false,
    add column if not exists privacy_accepted boolean default false,
    add column if not exists marketing_accepted boolean default false,
    add column if not exists terms_version text default '2026-07-13',
    add column if not exists privacy_version text default '2026-07-13',
    add column if not exists source text default 'signup',
    add column if not exists accepted_at timestamptz default now(),
    add column if not exists created_at timestamptz default now(),
    add column if not exists updated_at timestamptz default now();
update public.user_consents set terms_accepted = false where terms_accepted is null;
update public.user_consents set privacy_accepted = false where privacy_accepted is null;
update public.user_consents set marketing_accepted = false where marketing_accepted is null;
update public.user_consents set terms_version = '2026-07-13' where terms_version is null;
update public.user_consents set privacy_version = '2026-07-13' where privacy_version is null;
update public.user_consents set source = 'signup' where source is null;
update public.user_consents set accepted_at = now() where accepted_at is null;
update public.user_consents set created_at = now() where created_at is null;
update public.user_consents set updated_at = now() where updated_at is null;

do $$
declare
    next_id bigint;
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'properties'
          and column_name = 'id'
          and data_type in ('bigint', 'integer')
          and column_default is null
    ) then
        create sequence if not exists public.properties_legacy_id_seq;
        execute 'select coalesce(max(id), 0) + 1 from public.properties' into next_id;
        perform setval('public.properties_legacy_id_seq', greatest(next_id, 1), false);
        alter sequence public.properties_legacy_id_seq owned by public.properties.id;
        alter table public.properties
            alter column id set default nextval('public.properties_legacy_id_seq');
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'pricing_rules'
          and column_name = 'id'
          and data_type in ('bigint', 'integer')
          and column_default is null
    ) then
        create sequence if not exists public.pricing_rules_legacy_id_seq;
        execute 'select coalesce(max(id), 0) + 1 from public.pricing_rules' into next_id;
        perform setval('public.pricing_rules_legacy_id_seq', greatest(next_id, 1), false);
        alter sequence public.pricing_rules_legacy_id_seq owned by public.pricing_rules.id;
        alter table public.pricing_rules
            alter column id set default nextval('public.pricing_rules_legacy_id_seq');
    end if;
end $$;

alter table if exists public.guardrail_policies
    add column if not exists account_id bigint,
    add column if not exists local_id bigint,
    add column if not exists property_local_id bigint default 0;
update public.guardrail_policies set account_id = 1 where account_id is null;
update public.guardrail_policies set property_local_id = 0 where property_local_id is null;

alter table if exists public.price_calendar
    add column if not exists account_id bigint,
    add column if not exists local_id bigint,
    add column if not exists property_local_id bigint,
    add column if not exists date date;
update public.price_calendar set account_id = 1 where account_id is null;
update public.price_calendar set property_local_id = 0 where property_local_id is null;

alter table if exists public.decision_log
    add column if not exists account_id bigint,
    add column if not exists local_id bigint,
    add column if not exists property_local_id bigint,
    add column if not exists timestamp timestamptz default now();
update public.decision_log set account_id = 1 where account_id is null;
update public.decision_log set local_id = 0 where local_id is null;
update public.decision_log set property_local_id = 0 where property_local_id is null;

alter table if exists public.occupancy_history
    add column if not exists account_id bigint,
    add column if not exists local_id bigint,
    add column if not exists property_local_id bigint,
    add column if not exists date date;
update public.occupancy_history set account_id = 1 where account_id is null;
update public.occupancy_history set property_local_id = 0 where property_local_id is null;

alter table if exists public.market_history
    add column if not exists account_id bigint,
    add column if not exists local_id bigint,
    add column if not exists property_local_id bigint,
    add column if not exists date date;
update public.market_history set account_id = 1 where account_id is null;
update public.market_history set local_id = 0 where local_id is null;
update public.market_history set property_local_id = 0 where property_local_id is null;

alter table if exists public.telegram_links
    add column if not exists account_id bigint,
    add column if not exists local_id bigint,
    add column if not exists property_local_id bigint,
    add column if not exists token text;
update public.telegram_links set account_id = 1 where account_id is null;
update public.telegram_links set local_id = 0 where local_id is null;
update public.telegram_links set property_local_id = 0 where property_local_id is null;

alter table if exists public.telegram_approvals
    add column if not exists account_id bigint,
    add column if not exists local_id bigint,
    add column if not exists property_local_id bigint,
    add column if not exists decision_log_local_id bigint,
    add column if not exists telegram_link_local_id bigint,
    add column if not exists chat_id bigint,
    add column if not exists telegram_username text not null default '',
    add column if not exists status text not null default 'unknown',
    add column if not exists source text not null default 'telegram',
    add column if not exists message_id text not null default '',
    add column if not exists callback_query_id text not null default '',
    add column if not exists error text not null default '',
    add column if not exists payload jsonb not null default '{}'::jsonb,
    add column if not exists timestamp timestamptz default now(),
    add column if not exists updated_at timestamptz not null default now();
update public.telegram_approvals set account_id = 1 where account_id is null;
update public.telegram_approvals set local_id = 0 where local_id is null;
update public.telegram_approvals set property_local_id = 0 where property_local_id is null;
update public.telegram_approvals set decision_log_local_id = 0 where decision_log_local_id is null;
update public.telegram_approvals
set telegram_username = coalesce(nullif(telegram_username, ''), telegram_user, '')
where telegram_username = '' and telegram_user is not null;

alter table if exists public.property_integrations
    add column if not exists account_id bigint,
    add column if not exists local_id bigint,
    add column if not exists property_local_id bigint,
    add column if not exists platform text;
update public.property_integrations set account_id = 1 where account_id is null;
update public.property_integrations set local_id = 0 where local_id is null;
update public.property_integrations set property_local_id = 0 where property_local_id is null;

alter table if exists public.operation_runs
    add column if not exists account_id bigint,
    add column if not exists local_id bigint,
    add column if not exists started_at timestamptz default now();
update public.operation_runs set account_id = 1 where account_id is null;
update public.operation_runs set local_id = 0 where local_id is null;

alter table if exists public.audit_events
    add column if not exists account_id bigint,
    add column if not exists local_id bigint,
    add column if not exists timestamp timestamptz default now();
update public.audit_events set account_id = 1 where account_id is null;
update public.audit_events set local_id = 0 where local_id is null;

alter table if exists public.notification_preferences
    add column if not exists account_id bigint,
    add column if not exists local_id bigint,
    add column if not exists property_local_id bigint default 0;
update public.notification_preferences set account_id = 1 where account_id is null;
update public.notification_preferences set property_local_id = 0 where property_local_id is null;

alter table if exists public.notification_log
    add column if not exists account_id bigint,
    add column if not exists local_id bigint,
    add column if not exists property_local_id bigint,
    add column if not exists timestamp timestamptz default now();
update public.notification_log set account_id = 1 where account_id is null;
update public.notification_log set local_id = 0 where local_id is null;

create index if not exists idx_profiles_email
    on public.profiles(lower(email));
create index if not exists idx_account_members_user
    on public.account_members(user_id);
create index if not exists idx_user_consents_user
    on public.user_consents(user_id, accepted_at);
create index if not exists idx_properties_account
    on public.properties(account_id, local_id);
create index if not exists idx_pricing_rules_account
    on public.pricing_rules(account_id, property_local_id);
create unique index if not exists uq_user_consents_user_versions
    on public.user_consents(user_id, terms_version, privacy_version);
create unique index if not exists uq_properties_account_local
    on public.properties(account_id, local_id);
create unique index if not exists uq_pricing_rules_account_property
    on public.pricing_rules(account_id, property_local_id);
create index if not exists idx_guardrail_policies_account
    on public.guardrail_policies(account_id, property_local_id);
create index if not exists idx_price_calendar_account
    on public.price_calendar(account_id, property_local_id, date);
create index if not exists idx_decision_log_account
    on public.decision_log(account_id, property_local_id, timestamp);
create index if not exists idx_occupancy_history_account
    on public.occupancy_history(account_id, property_local_id, date);
create index if not exists idx_market_history_account
    on public.market_history(account_id, property_local_id, date);
create index if not exists idx_telegram_links_account
    on public.telegram_links(account_id, property_local_id);
create index if not exists idx_telegram_approvals_account
    on public.telegram_approvals(account_id, timestamp);
create index if not exists idx_telegram_approvals_decision
    on public.telegram_approvals(account_id, decision_log_local_id);
create index if not exists idx_property_integrations_account
    on public.property_integrations(account_id, property_local_id);
create index if not exists idx_operation_runs_account
    on public.operation_runs(account_id, started_at);
create index if not exists idx_audit_events_account
    on public.audit_events(account_id, timestamp);
create index if not exists idx_notification_preferences_account
    on public.notification_preferences(account_id, property_local_id);
create index if not exists idx_notification_log_account
    on public.notification_log(account_id, timestamp);

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_accounts_updated_at on public.accounts;
create trigger set_accounts_updated_at
before update on public.accounts
for each row execute function public.set_updated_at();

drop trigger if exists set_account_members_updated_at on public.account_members;
create trigger set_account_members_updated_at
before update on public.account_members
for each row execute function public.set_updated_at();

drop trigger if exists set_user_consents_updated_at on public.user_consents;
create trigger set_user_consents_updated_at
before update on public.user_consents
for each row execute function public.set_updated_at();

drop trigger if exists set_properties_updated_at on public.properties;
create trigger set_properties_updated_at
before update on public.properties
for each row execute function public.set_updated_at();

drop trigger if exists set_pricing_rules_updated_at on public.pricing_rules;
create trigger set_pricing_rules_updated_at
before update on public.pricing_rules
for each row execute function public.set_updated_at();

drop trigger if exists set_guardrail_policies_updated_at on public.guardrail_policies;
create trigger set_guardrail_policies_updated_at
before update on public.guardrail_policies
for each row execute function public.set_updated_at();

drop trigger if exists set_price_calendar_updated_at on public.price_calendar;
create trigger set_price_calendar_updated_at
before update on public.price_calendar
for each row execute function public.set_updated_at();

drop trigger if exists set_decision_log_updated_at on public.decision_log;
create trigger set_decision_log_updated_at
before update on public.decision_log
for each row execute function public.set_updated_at();

drop trigger if exists set_occupancy_history_updated_at on public.occupancy_history;
create trigger set_occupancy_history_updated_at
before update on public.occupancy_history
for each row execute function public.set_updated_at();

drop trigger if exists set_market_history_updated_at on public.market_history;
create trigger set_market_history_updated_at
before update on public.market_history
for each row execute function public.set_updated_at();

drop trigger if exists set_telegram_links_updated_at on public.telegram_links;
create trigger set_telegram_links_updated_at
before update on public.telegram_links
for each row execute function public.set_updated_at();

drop trigger if exists set_telegram_approvals_updated_at on public.telegram_approvals;
create trigger set_telegram_approvals_updated_at
before update on public.telegram_approvals
for each row execute function public.set_updated_at();

drop trigger if exists set_property_integrations_updated_at on public.property_integrations;
create trigger set_property_integrations_updated_at
before update on public.property_integrations
for each row execute function public.set_updated_at();

drop trigger if exists set_operation_runs_updated_at on public.operation_runs;
create trigger set_operation_runs_updated_at
before update on public.operation_runs
for each row execute function public.set_updated_at();

drop trigger if exists set_audit_events_updated_at on public.audit_events;
create trigger set_audit_events_updated_at
before update on public.audit_events
for each row execute function public.set_updated_at();

drop trigger if exists set_notification_preferences_updated_at on public.notification_preferences;
create trigger set_notification_preferences_updated_at
before update on public.notification_preferences
for each row execute function public.set_updated_at();

drop trigger if exists set_notification_log_updated_at on public.notification_log;
create trigger set_notification_log_updated_at
before update on public.notification_log
for each row execute function public.set_updated_at();

create or replace function private.is_account_member(p_account_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
    select exists (
        select 1
        from public.account_members m
        where m.account_id = p_account_id
          and m.user_id = auth.uid()
    );
$$;

create or replace function private.is_account_owner(p_account_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
    select exists (
        select 1
        from public.account_members m
        where m.account_id = p_account_id
          and m.user_id = auth.uid()
          and m.role = 'owner'
    );
$$;

create or replace function private.owns_account_record(p_account_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
    select exists (
        select 1
        from public.accounts a
        where a.id = p_account_id
          and a.owner_user_id = auth.uid()
    );
$$;

revoke all on function private.is_account_member(bigint) from public;
revoke all on function private.is_account_member(bigint) from anon;
revoke all on function private.is_account_member(bigint) from authenticated;
revoke all on function private.is_account_owner(bigint) from public;
revoke all on function private.is_account_owner(bigint) from anon;
revoke all on function private.is_account_owner(bigint) from authenticated;
revoke all on function private.owns_account_record(bigint) from public;
revoke all on function private.owns_account_record(bigint) from anon;
revoke all on function private.owns_account_record(bigint) from authenticated;

alter table public.profiles enable row level security;
alter table public.accounts enable row level security;
alter table public.account_members enable row level security;
alter table public.user_consents enable row level security;
alter table public.properties enable row level security;
alter table public.pricing_rules enable row level security;
alter table public.guardrail_policies enable row level security;
alter table public.price_calendar enable row level security;
alter table public.decision_log enable row level security;
alter table public.occupancy_history enable row level security;
alter table public.market_history enable row level security;
alter table public.telegram_links enable row level security;
alter table public.telegram_approvals enable row level security;
alter table public.property_integrations enable row level security;
alter table public.operation_runs enable row level security;
alter table public.audit_events enable row level security;
alter table public.notification_preferences enable row level security;
alter table public.notification_log enable row level security;

-- Remove old permissive demo policies if they exist.
drop policy if exists "pricepilot_properties_anon_sync" on public.properties;
drop policy if exists "pricepilot_pricing_rules_anon_sync" on public.pricing_rules;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (id = auth.uid());

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check (id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "accounts_select_member" on public.accounts;
create policy "accounts_select_member"
on public.accounts
for select
to authenticated
using (owner_user_id = auth.uid() or private.is_account_member(id));

drop policy if exists "accounts_insert_owner" on public.accounts;
create policy "accounts_insert_owner"
on public.accounts
for insert
to authenticated
with check (owner_user_id = auth.uid());

drop policy if exists "accounts_update_owner" on public.accounts;
create policy "accounts_update_owner"
on public.accounts
for update
to authenticated
using (owner_user_id = auth.uid() or private.is_account_owner(id))
with check (owner_user_id = auth.uid() or private.is_account_owner(id));

drop policy if exists "account_members_select_member" on public.account_members;
create policy "account_members_select_member"
on public.account_members
for select
to authenticated
using (private.is_account_member(account_id) or private.owns_account_record(account_id));

drop policy if exists "account_members_insert_owner" on public.account_members;
create policy "account_members_insert_owner"
on public.account_members
for insert
to authenticated
with check (
    (
        user_id = auth.uid()
        and role = 'owner'
        and private.owns_account_record(account_id)
    )
    or private.is_account_owner(account_id)
);

drop policy if exists "account_members_update_owner" on public.account_members;
create policy "account_members_update_owner"
on public.account_members
for update
to authenticated
using (private.is_account_owner(account_id))
with check (private.is_account_owner(account_id));

drop policy if exists "account_members_delete_owner" on public.account_members;
create policy "account_members_delete_owner"
on public.account_members
for delete
to authenticated
using (private.is_account_owner(account_id));

drop policy if exists "user_consents_own_all" on public.user_consents;
create policy "user_consents_own_all"
on public.user_consents
for all
to authenticated
using (user_id = auth.uid() and private.is_account_member(account_id))
with check (user_id = auth.uid() and private.is_account_member(account_id));

drop policy if exists "properties_member_all" on public.properties;
create policy "properties_member_all"
on public.properties
for all
to authenticated
using (private.is_account_member(account_id))
with check (private.is_account_member(account_id));

drop policy if exists "pricing_rules_member_all" on public.pricing_rules;
create policy "pricing_rules_member_all"
on public.pricing_rules
for all
to authenticated
using (private.is_account_member(account_id))
with check (private.is_account_member(account_id));

drop policy if exists "guardrail_policies_member_all" on public.guardrail_policies;
create policy "guardrail_policies_member_all"
on public.guardrail_policies
for all
to authenticated
using (private.is_account_member(account_id))
with check (private.is_account_member(account_id));

drop policy if exists "price_calendar_member_all" on public.price_calendar;
create policy "price_calendar_member_all"
on public.price_calendar
for all
to authenticated
using (private.is_account_member(account_id))
with check (private.is_account_member(account_id));

drop policy if exists "decision_log_member_all" on public.decision_log;
create policy "decision_log_member_all"
on public.decision_log
for all
to authenticated
using (private.is_account_member(account_id))
with check (private.is_account_member(account_id));

drop policy if exists "occupancy_history_member_all" on public.occupancy_history;
create policy "occupancy_history_member_all"
on public.occupancy_history
for all
to authenticated
using (private.is_account_member(account_id))
with check (private.is_account_member(account_id));

drop policy if exists "market_history_member_all" on public.market_history;
create policy "market_history_member_all"
on public.market_history
for all
to authenticated
using (private.is_account_member(account_id))
with check (private.is_account_member(account_id));

drop policy if exists "telegram_links_member_all" on public.telegram_links;
create policy "telegram_links_member_all"
on public.telegram_links
for all
to authenticated
using (private.is_account_member(account_id))
with check (private.is_account_member(account_id));

drop policy if exists "telegram_approvals_member_all" on public.telegram_approvals;
create policy "telegram_approvals_member_all"
on public.telegram_approvals
for all
to authenticated
using (private.is_account_member(account_id))
with check (private.is_account_member(account_id));

drop policy if exists "property_integrations_member_all" on public.property_integrations;
create policy "property_integrations_member_all"
on public.property_integrations
for all
to authenticated
using (private.is_account_member(account_id))
with check (private.is_account_member(account_id));

drop policy if exists "operation_runs_member_all" on public.operation_runs;
create policy "operation_runs_member_all"
on public.operation_runs
for all
to authenticated
using (private.is_account_member(account_id))
with check (private.is_account_member(account_id));

drop policy if exists "audit_events_member_all" on public.audit_events;
create policy "audit_events_member_all"
on public.audit_events
for all
to authenticated
using (private.is_account_member(account_id))
with check (private.is_account_member(account_id));

drop policy if exists "notification_preferences_member_all" on public.notification_preferences;
create policy "notification_preferences_member_all"
on public.notification_preferences
for all
to authenticated
using (private.is_account_member(account_id))
with check (private.is_account_member(account_id));

drop policy if exists "notification_log_member_all" on public.notification_log;
create policy "notification_log_member_all"
on public.notification_log
for all
to authenticated
using (private.is_account_member(account_id))
with check (private.is_account_member(account_id));

drop function if exists public.is_account_member(bigint);
drop function if exists public.is_account_owner(bigint);
drop function if exists public.owns_account_record(bigint);
